namespace Requests.Ecobee
{
    public class Alert
    {
        /// <summary>
        /// The unique alert identifier.This is required to acknowledge an alert.
        /// </summary>
        public string acknowledgeRef;
        /// <summary>
        /// The alert date: YYYY-MM-DD
        /// </summary>
        public string date;
        /// <summary>
        /// The alert time: HH:MM:SS
        /// </summary>
        public string time;
        /// <summary>
        /// The alert severity. Values: low, medium, high.
        /// </summary>
        public string severity;
        /// <summary>
        /// The alert message text. Will be truncated to 500 characters if longer.
        /// </summary>
        public string text;
        /// <summary>
        /// The ecobee alert message identifier
        /// </summary>
        public int alertNumber;
        /// <summary>
        /// The type of alert this is. Values: alert, demandResponse, emergency, message, pricing.
        /// </summary>
        public string alertType;
        /// <summary>
        /// Whether the alert was generated by the thermostat owner
        /// </summary>
        public bool isOperatorAlert;
        /// <summary>
        /// Whether a reminder will be sent.
        /// </summary>
        public string reminder;
        /// <summary>
        /// Whether to show the alert on the thermostat.
        /// </summary>
        public bool showIdt;
        /// <summary>
        /// Whether to show the alert on the ecobee web portal.
        /// </summary>
        public bool showWeb;
        /// <summary>
        /// Whether to send an alert email to the thermostat user.
        /// </summary>
        public bool sendEmail;
        /// <summary>
        /// The user acknowledgement type. Values: accept, decline, defer, unacknowledged.
        /// </summary>
        public string acknowledgement;
        /// <summary>
        /// Whether to remind the user at a later time about the alert.
        /// </summary>
        public bool remindMeLater;
        /// <summary>
        /// The identifier of the thermostat that generated the alert
        /// </summary>
        public string thermostatIdentifier;
        /// <summary>
        /// The type of Alert or reminder.  If the configuration for the specific alert type is required,
        /// Possible values are: 
        ///     alert, hvac, furnaceFilter, humidifierFilter,
        ///     dehumidifierFilter, ventilator, ac, airFilter,
        ///     airCleaner, uvLamp, temp, lowTemp, highTemp,
        ///     lowHumidity, highHumidity, auxHeat, auxOutdoor.
        /// </summary>
        public string notificationType;
    }
}