namespace Requests.Ecobee
{
    public class Settings
    {
        public string hvacMode { get; set; }
        public string lastServiceDate { get; set; }
        public bool serviceRemindMe { get; set; }
        public int monthsBetweenService { get; set; }
        public string remindMeDate { get; set; }
        public string vent { get; set; }
        public int ventilatorMinOnTime { get; set; }
        public bool serviceRemindTechnician { get; set; }
        public string eiLocation { get; set; }
        public int coldTempAlert { get; set; }
        public bool coldTempAlertEnabled { get; set; }
        public int hotTempAlert { get; set; }
        public bool hotTempAlertEnabled { get; set; }
        public int coolStages { get; set; }
        public int heatStages { get; set; }
        public int maxSetBack { get; set; }
        public int maxSetForward { get; set; }
        public int quickSaveSetBack { get; set; }
        public int quickSaveSetForward { get; set; }
        public bool hasHeatPump { get; set; }
        public bool hasForcedAir { get; set; }
        public bool hasBoiler { get; set; }
        public bool hasHumidifier { get; set; }
        public bool hasErv { get; set; }
        public bool hasHrv { get; set; }
        public bool condensationAvoid { get; set; }
        public bool useCelsius { get; set; }
        public bool useTimeFormat12 { get; set; }
        public string locale { get; set; }
        public string humidity { get; set; }
        public string humidifierMode { get; set; }
        public int backlightOnIntensity { get; set; }
        public int backlightSleepIntensity { get; set; }
        public int backlightOffTime { get; set; }
        public int soundTickVolume { get; set; }
        public int soundAlertVolume { get; set; }
        public int compressorProtectionMinTime { get; set; }
        public int compressorProtectionMinTemp { get; set; }
        public int stage1HeatingDifferentialTemp { get; set; }
        public int stage1CoolingDifferentialTemp { get; set; }
        public int stage1HeatingDissipationTime { get; set; }
        public int stage1CoolingDissipationTime { get; set; }
        public bool heatPumpReversalOnCool { get; set; }
        public bool fanControlRequired { get; set; }
        public int fanMinOnTime { get; set; }
        public int heatCoolMinDelta { get; set; }
        public int tempCorrection { get; set; }
        public string holdAction { get; set; }
        public bool heatPumpGroundWater { get; set; }
        public bool hasElectric { get; set; }
        public bool hasDehumidifier { get; set; }
        public string dehumidifierMode { get; set; }
        public int dehumidifierLevel { get; set; }
        public bool dehumidifyWithAC { get; set; }
        public int dehumidifyOvercoolOffset { get; set; }
        public bool autoHeatCoolFeatureEnabled { get; set; }
        public bool wifiOfflineAlert { get; set; }
        public int heatMinTemp { get; set; }
        public int heatMaxTemp { get; set; }
        public int coolMinTemp { get; set; }
        public int coolMaxTemp { get; set; }
        public int heatRangeHigh { get; set; }
        public int heatRangeLow { get; set; }
        public int coolRangeHigh { get; set; }
        public int coolRangeLow { get; set; }
        public string userAccessCode { get; set; }
        public int userAccessSetting { get; set; }
        public int auxRuntimeAlert { get; set; }
        public int auxOutdoorTempAlert { get; set; }
        public int auxMaxOutdoorTemp { get; set; }
        public bool auxRuntimeAlertNotify { get; set; }
        public bool auxOutdoorTempAlertNotify { get; set; }
        public bool auxRuntimeAlertNotifyTechnician { get; set; }
        public bool auxOutdoorTempAlertNotifyTechnician { get; set; }
        public bool disablePreHeating { get; set; }
        public bool disablePreCooling { get; set; }
        public bool installerCodeRequired { get; set; }
        public string drAccept { get; set; }
        public bool isRentalProperty { get; set; }
        public bool useZoneController { get; set; }
        public int randomStartDelayCool { get; set; }
        public int randomStartDelayHeat { get; set; }
        public int humidityHighAlert { get; set; }
        public int humidityLowAlert { get; set; }
        public bool disableHeatPumpAlerts { get; set; }
        public bool disableAlertsOnIdt { get; set; }
        public bool humidityAlertNotify { get; set; }
        public bool humidityAlertNotifyTechnician { get; set; }
        public bool tempAlertNotify { get; set; }
        public bool tempAlertNotifyTechnician { get; set; }
        public int monthlyElectricityBillLimit { get; set; }
        public bool enableElectricityBillAlert { get; set; }
        public bool enableProjectedElectricityBillAlert { get; set; }
        public int electricityBillingDayOfMonth { get; set; }
        public int electricityBillCycleMonths { get; set; }
        public int electricityBillStartMonth { get; set; }
        public int ventilatorMinOnTimeHome { get; set; }
        public int ventilatorMinOnTimeAway { get; set; }
        public bool backlightOffDuringSleep { get; set; }
        public bool autoAway { get; set; }
        public bool smartCirculation { get; set; }
        public bool followMeComfort { get; set; }
        public string ventilatorType { get; set; }
        public bool isVentilatorTimerOn { get; set; }
        public string ventilatorOffDateTime { get; set; }
        public bool hasUVFilter { get; set; }
        public bool coolingLockout { get; set; }
        public bool ventilatorFreeCooling { get; set; }
        public bool dehumidifyWhenHeating { get; set; }
        public bool ventilatorDehumidify { get; set; }
        public string groupRef { get; set; }
        public string groupName { get; set; }
        public int groupSetting { get; set; }
    }
}
